name: restaurant_search_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/restaurant_a.jpg
    - assets/restaurant_b.jpg
    - assets/restaurant_c.jpg
    - assets/restaurant_e.jpg
    - assets/restaurant_f.jpg
    - assets/restaurant_g.jpg